### ISSUE TITLE
1.12 breaks the plugin

### ISSUE THREAD

**Issue by GriffinCodes** [Nokorbis/ar-command-signs#11]
```
[11:26:28] [Server thread/INFO]: [CommandSigns] Enabling CommandSigns v1.9.3.2
[11:26:28] [Server thread/ERROR]: Error occurred while enabling CommandSigns v1.9.3.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at org.zonedabone.commandsigns.util.YamlLoader.loadResource(YamlLoader.java:26) ~[?:?]
        at org.zonedabone.commandsigns.config.Config.load(Config.java:14) ~[?:?]
        at org.zonedabone.commandsigns.CommandSigns.load(CommandSigns.java:71) ~[?:?]
        at org.zonedabone.commandsigns.CommandSigns.onEnable(CommandSigns.java:92) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-6629162-cda27c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

If you weren't aware, spigot has released 1.12 pre-release versions. Check the homepage for more details

**Comment by Nokorbis** [comment]
Hello there ! That does not look like my plugin. Probably just one that has the same name as mine. :/

**Comment by GriffinCodes** [comment]
Oh crap, my bad.
