### ISSUE TITLE
Null EventException

### ISSUE THREAD

**Issue by Paperboypaddy** [Nokorbis/ar-command-signs#24]
Welp this is great I installed it and im getting a null exception :(
Says its caused by: java.lang.NoSuchFieldError: ACACIA_PRESSURE_PLATE. Not exactly why id be doing this. I was doing "/commandsigns create" and I right clicked and it wasn't getting my input. 

`[12:23:21 ERROR]: Could not pass event PlayerInteractEvent to CommandSigns v1.6.8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchFieldError: ACACIA_PRESSURE_PLATE
	at be.nokorbis.spigot.commandsigns.utils.CommandSignUtils.isPlate(CommandSignUtils.java:22) ~[?:?]
	at be.nokorbis.spigot.commandsigns.utils.CommandSignUtils.isValidBlock(CommandSignUtils.java:72) ~[?:?]
	at be.nokorbis.spigot.commandsigns.controller.CommandSignListener.createCommandBlock(CommandSignListener.java:258) ~[?:?]
	at be.nokorbis.spigot.commandsigns.controller.CommandSignListener.onInteractEvent(CommandSignListener.java:146) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot12.jar:git-Spigot-596221b-9a1fc1e]
	... 17 more`

**Comment by Nokorbis** [comment]
Hey, I see in the logs you are using Spigot 12 and not 13

Use Command Signs version 1.6.7 then :) (it has exact same features, but it supports only up to spigot 12.2)
You can find it here : https://www.spigotmc.org/resources/command-signs.10512/history
